# Generated by Django 5.0.1 on 2024-01-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comesout',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='days',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='tours',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='comesout',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='days',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tours',
            name='price_for_one',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='tours',
            name='price_for_two',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='tours',
            name='title_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
