# Generated by Django 5.0.1 on 2024-01-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_datetours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tours',
            old_name='description',
            new_name='description_en',
        ),
        migrations.AddField(
            model_name='tours',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
