# Generated by Django 5.0.1 on 2024-01-31 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_rename_description_tours_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToursImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mainimg', models.FileField(upload_to='toursIMG/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tours')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
