# Generated by Django 5.0.1 on 2024-01-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0005_toursimg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tours",
            name="mainimg",
            field=models.FileField(upload_to="tour/"),
        ),
    ]
