# Generated by Django 5.0.1 on 2024-02-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_remove_tours_price_for_one_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_for_one_bussines', models.CharField(blank=True, default=0, max_length=56, null=True)),
                ('price_for_two_bussines', models.CharField(blank=True, default=0, max_length=56, null=True)),
                ('price_for_one_wine', models.CharField(blank=True, default=0, max_length=56, null=True)),
                ('price_for_two_wine', models.CharField(blank=True, default=0, max_length=56, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tours',
            name='price_for_one_bussines',
        ),
        migrations.RemoveField(
            model_name='tours',
            name='price_for_one_wine',
        ),
        migrations.RemoveField(
            model_name='tours',
            name='price_for_two_bussines',
        ),
        migrations.RemoveField(
            model_name='tours',
            name='price_for_two_wine',
        ),
    ]
