# Generated by Django 5.0.1 on 2024-02-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_pricefor_remove_tours_price_for_one_bussines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateAUTUMNTours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_en', models.CharField(blank=True, max_length=256, null=True)),
                ('day_ru', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
