# Generated by Django 5.0.1 on 2024-01-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_delete_tours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RemoveField(
            model_name='stepbystep',
            name='title',
        ),
        migrations.AddField(
            model_name='country',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='title_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='stepbystep',
            name='title_en',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='stepbystep',
            name='title_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
